# -*- coding: utf-8 -*-
"""Untitled29.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19v9FK16D2t7LmOmqffvxb0MGho7G4r7k

#Import libraries
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

"""#Load Dataset"""

# load data

df = pd.read_csv("player_metrics_all_formats.csv")

# View first rows
df.head()

print(df.columns)

# standardise column names 

df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

# RENAME COLUMNS

df = df.rename(columns={
    "runsperinnings": "runs_per_innings",
    "runspermatch": "runs_per_match",
    "boundarypercentage": "boundary_percentage",
    "dotballpercentage": "dot_ball_percentage",
    "strikerate": "strike_rate",
    "ballsfaced": "balls_faced",
    "dotballs": "dot_balls"
})


# CLEAN TEXT COLUMNS

df["batter"] = df["batter"].astype(str).str.strip()
df["format"] = df["format"].astype(str).str.strip()

# HANDLE MISSING VALUES

numeric_cols = df.select_dtypes(include=["int64", "float64"]).columns

for col in numeric_cols:
    df[col] = df[col].fillna(df[col].median())


# REMOVE DUPLICATES 

df = df.drop_duplicates()

#final check

print("Cleaned Shape:", df.shape)
print("\nMissing Values:\n", df.isnull().sum())

"""#Quick EDA(Exploratory Data Analysis)"""

df.head()

df.describe()

df.info()

features_to_plot = ["average", "strike_rate"]

plt.figure(figsize=(15,4))

for i, col in enumerate(features_to_plot, 1):
    plt.subplot(1,3,i)
    sns.histplot(df[col], kde=True)
    plt.title(f"Distribution of {col}")

plt.tight_layout()
plt.show()

# plotting of batting average

plt.figure(figsize=(10,5))
sns.boxplot(x="format", y="average", data=df)

plt.title("Batting Average Across Formats")
plt.show()

# plotting of st rate

plt.figure(figsize=(10,5))
sns.boxplot(x="format", y="strike_rate", data=df)

plt.title("Strike Rate Across Formats")
plt.show()

# Heat map plotting

plt.figure(figsize=(12,10))

# Select only numeric columns
corr = df.select_dtypes(include=["int64", "float64"]).corr()

# Plot heatmap
sns.heatmap(
    corr,
    annot=True,          # show values inside cells
    fmt=".2f",           # 2 decimal places
    cmap="coolwarm",     # color theme
    linewidths=0.5,      # grid lines
    square=True,         # square cells
    cbar_kws={"shrink": 0.8}
)

plt.title("Correlation Heatmap of Batting Performance Features", fontsize=14)

plt.xticks(rotation=45, ha="right")
plt.yticks(rotation=0)

plt.tight_layout()
plt.show()

#highly corellated features

import numpy as np

corr_matrix = df.select_dtypes(include=["int64", "float64"]).corr().abs()

upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))

high_corr_features = [col for col in upper.columns if any(upper[col] > 0.85)]

print("Highly Correlated Features:\n", high_corr_features)

# Performance-based elite definition
df["performance_score"] = (
    df["average"] * 0.4 +
    df["strike_rate"] * 0.3 +
    df["runs_per_match"] * 0.3
)

threshold = df["performance_score"].quantile(0.90)

df["elite"] = (df["performance_score"] >= threshold).astype(int)

print(df["elite"].value_counts())

#creating new important batting features

df["consistency_index"] = df["average"] / (df["innings"] + 1)
df["runs_per_ball"] = df["runs"] / (df["balls_faced"] + 1)
df["boundary_rate"] = df["boundaries"] / (df["runs"] + 1)
df["dot_ball_pressure"] = df["dot_balls"] / (df["balls_faced"] + 1)

df["format_adaptability"] = (
    df["testscore"] + df["odiscore"] + df["t20score"]
) / 3

features = [
    "strike_rate",
    "boundary_percentage",
    "dot_ball_percentage",
    "consistency_index",
    "runs_per_ball",
    "boundary_rate",
    "dot_ball_pressure",
    "format_adaptability"
]

X = df[features]
y = df["elite"]

sns.barplot(x="elite", y="strike_rate", data=df)
plt.title("Average Strike Rate by Elite Status")
plt.show()

#train test split

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)



from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

feature_names = features

# Choosing models

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC

# Models
lr = LogisticRegression(max_iter=1000)
rf = RandomForestClassifier(random_state=42)
svm = SVC(probability=True)


# Train
lr.fit(X_train, y_train)
rf.fit(X_train, y_train)
svm.fit(X_train, y_train)

# 

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

results = []

def evaluate(name, model):
    y_pred = model.predict(X_test)

    results.append({
        "Model": name,
        "Accuracy": accuracy_score(y_test, y_pred),
        "Precision": precision_score(y_test, y_pred),
        "Recall": recall_score(y_test, y_pred),
        "F1": f1_score(y_test, y_pred)
    })

evaluate("Logistic Regression", lr)
evaluate("Random Forest", rf)
evaluate("SVM", svm)


results_df = pd.DataFrame(results)
results_df.sort_values(by="F1", ascending=False)



import time

results = []

def train_and_evaluate(model, model_name):

    #TRAIN
    start_train = time.time()
    model.fit(X_train, y_train)
    end_train = time.time()

    # TEST
    start_test = time.time()
    y_pred = model.predict(X_test)
    end_test = time.time()

    # METRICS
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)

    #STORE RESULTS
    results.append({
        "Model": model_name,
        "Accuracy": accuracy,
        "Precision": precision,
        "Recall": recall,
        "F1": f1,
        "Train_Time": end_train - start_train,
        "Test_Time": end_test - start_test
    })

# Code Cell

# Initialize models
lr = LogisticRegression(max_iter=1000)
rf = RandomForestClassifier(random_state=42)
svm = SVC(probability=True)


# Train & evaluate
train_and_evaluate(lr, "Logistic Regression")
train_and_evaluate(rf, "Random Forest")
train_and_evaluate(svm, "SVM")


# Convert to DataFrame
results_df = pd.DataFrame(results)

# Sort by F1-score
results_df.sort_values(by="F1", ascending=False)

# confusion matrix plots

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

def plot_cm(model, name):
    y_pred = model.predict(X_test)
    cm = confusion_matrix(y_test, y_pred)

    plt.figure(figsize=(5,4))
    sns.heatmap(cm, annot=True, fmt="d", cmap="Blues")

    plt.title(f"Confusion Matrix - {name}")
    plt.xlabel("Predicted")
    plt.ylabel("Actual")

    plt.show()

plot_cm(lr, "Logistic Regression")
plot_cm(rf, "Random Forest")
plot_cm(svm, "SVM")

# plotting ROC curve for models

from sklearn.metrics import roc_curve, auc

plt.figure(figsize=(8,6))

models = {
    "LR": lr,
    "RF": rf,
    "SVM": svm,

}

for name, model in models.items():
    y_prob = model.predict_proba(X_test)[:,1]

    fpr, tpr, _ = roc_curve(y_test, y_prob)
    roc_auc = auc(fpr, tpr)

    plt.plot(fpr, tpr, label=f"{name} (AUC={roc_auc:.3f})")

plt.plot([0,1], [0,1], linestyle="--")

plt.xlabel("FPR")
plt.ylabel("TPR")
plt.title("ROC Curve")
plt.legend()

plt.show()

#hyoer parameter tuning

from sklearn.model_selection import GridSearchCV

lr_params = {"C": [0.1, 1, 10]}

lr_grid = GridSearchCV(LogisticRegression(max_iter=1000), lr_params, cv=3, scoring="f1")
lr_grid.fit(X_train, y_train)

best_lr = lr_grid.best_estimator_

# tuning of random forest

rf_params = {
    "n_estimators": [100, 200],
    "max_depth": [None, 10],
}

rf_grid = GridSearchCV(RandomForestClassifier(), rf_params, cv=3, scoring="f1")
rf_grid.fit(X_train, y_train)

best_rf = rf_grid.best_estimator_

# svm tuning

svm_params = {
    "C": [0.1, 1, 10],
    "kernel": ["linear", "rbf"]
}

svm_grid = GridSearchCV(SVC(probability=True), svm_params, cv=3, scoring="f1")
svm_grid.fit(X_train, y_train)

best_svm = svm_grid.best_estimator_

#

gb_params = {
    "n_estimators": [100, 200],
    "learning_rate": [0.01, 0.1]
}

gb_grid = GridSearchCV(GradientBoostingClassifier(), gb_params, cv=3, scoring="f1")
gb_grid.fit(X_train, y_train)

best_gb = gb_grid.best_estimator_

#important features of Random forest

import pandas as pd

importances = best_rf.feature_importances_

fi = pd.DataFrame({
    "feature": feature_names,
    "importance": importances
}).sort_values(by="importance", ascending=False)

fi.plot(kind="bar", x="feature", y="importance")
plt.title("Feature Importance - Random Forest")
plt.xticks(rotation=45)
plt.show()

#confusion matrix for models

def plot_cm(model, name):
    y_pred = model.predict(X_test)
    cm = confusion_matrix(y_test, y_pred)

    plt.figure(figsize=(5,4))
    sns.heatmap(cm, annot=True, fmt="d", cmap="Blues")

    plt.title(f"Confusion Matrix - {name}")
    plt.xlabel("Predicted")
    plt.ylabel("Actual")

    plt.show()

# Tuned models confusion matrix plot
plot_cm(best_lr, "Tuned Logistic Regression")
plot_cm(best_rf, "Tuned Random Forest")
plot_cm(best_svm, "Tuned SVM")

# roc for tuned models

from sklearn.metrics import roc_curve, auc

plt.figure(figsize=(8,6))

tuned_models = {
    "Tuned LR": best_lr,
    "Tuned RF": best_rf,
    "Tuned SVM": best_svm,

}

for name, model in tuned_models.items():

    y_prob = model.predict_proba(X_test)[:,1]

    fpr, tpr, _ = roc_curve(y_test, y_prob)
    roc_auc = auc(fpr, tpr)

    plt.plot(fpr, tpr, label=f"{name} (AUC={roc_auc:.3f})")

plt.plot([0,1], [0,1], linestyle="--")

plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve - Tuned Models")
plt.legend()

plt.show()

print(fi)

final_table = results_df.copy()

# Convert time to milliseconds (cleaner for PPT)
final_table["Train_Time(ms)"] = final_table["Train_Time"] * 1000
final_table["Test_Time(ms)"] = final_table["Test_Time"] * 1000

# Drop original time columns
final_table = final_table.drop(columns=["Train_Time", "Test_Time"])

# Round values
final_table = final_table.round(4)

final_table.sort_values(by="F1", ascending=False)